/* SKU key -> English page slug (products/<slug>.html). Single source of truth for
   hreflang wiring, used by gen-product-i18n.js (localized pages) and wire-hreflang-en.js (EN pages). */
module.exports = {
  p1:'solar-motion-flood-light-3-head',
  p2:'pir-motion-sensor-wall-light',
  p7:'solar-flood-security-light-30w',
  p10:'up-down-solar-wall-light',
  p9:'all-in-one-solar-street-light',
  p27:'split-solar-street-light',
  p25:'solar-warning-beacon-light',
  p26:'solar-flag-pole-light',
  p28:'solar-courtyard-column-light',
  p6:'solar-garden-stake-light-8-pack',
  p8:'solar-garden-spike-spotlight',
  p4:'outdoor-wall-lantern-solar-ac',
  p11:'solar-edison-string-lights',
  p19:'solar-flame-torch-light',
  p20:'solar-fairy-copper-wire-string-lights',
  p21:'solar-umbrella-light',
  p22:'solar-outdoor-floor-lamp',
  p29:'solar-pool-float-light',
  p15:'solar-indoor-wall-light-split-panel',
  p16:'solar-emergency-led-bulb',
  p17:'solar-home-lighting-kit',
  p18:'solar-ceiling-fan-with-light',
  p13:'solar-portable-camping-lantern',
  p14:'solar-bug-zapper-light',
  p23:'solar-portable-work-light',
  p24:'solar-power-bank-lantern-pro',
  p30:'emergency-ufo-rechargeable-light',
  p31:'ac-led-floodlight',
  p32:'ufo-high-bay-light',
  p33:'ac-street-light',
};
